"""GridScope energy analysis engine."""

from gridscope.analysis import (
    DEFAULT_PLANS,
    DEFAULT_TARIFF,
    VERSION,
    GridScopeError,
    apply_tou,
    compare_datasets,
    compare_plans,
    data_quality,
    dedupe_rows,
    estimate_bill,
    filter_household,
    get_analysis,
    get_anomalies,
    load_csv,
    parse_date_and_hour,
    parse_energy_csv,
    shift_peak,
    weekday_heatmap,
    weekend_split,
    what_if_peak_shift,
    what_if_solar_self,
)

__version__ = VERSION

__all__ = [
    "DEFAULT_PLANS",
    "DEFAULT_TARIFF",
    "VERSION",
    "GridScopeError",
    "apply_tou",
    "compare_datasets",
    "compare_plans",
    "data_quality",
    "dedupe_rows",
    "estimate_bill",
    "filter_household",
    "get_analysis",
    "get_anomalies",
    "load_csv",
    "parse_date_and_hour",
    "parse_energy_csv",
    "shift_peak",
    "weekday_heatmap",
    "weekend_split",
    "what_if_peak_shift",
    "what_if_solar_self",
]
